apiVersion: v1
kind: Pod
metadata:
  name: sync-app
  namespace: ckad
  labels:
    app: sidecar
spec:
  volumes:
    - name: html
      emptyDir: {}
  containers:
  - name: syncer
    image: k8s.gcr.io/git-sync:v3.1.6
    volumeMounts:
    - name: html
      mountPath: /tmp/git/
    env:
    - name: GIT_SYNC_REPO
      value: https://github.com/nigelpoulton/ps-sidecar.git
    - name: GIT_SYNC_BRANCH
      value: master
    - name: GIT_SYNNC_DEPTH
      value: "1"
    - name: GIT_SYNC_DEST
      value: "html"
  - name: main-app
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/

---
apiVersion: v1
kind: Service
metadata:
  name: svc-sidecar
  namespace: ckad
spec:
  selector:
    app: sidecar
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001

