apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-test
spec:
  replicas: 3
  selector:
    matchLabels:
      course: ckad
  template:
    metadata:
      labels:
        course: ckad
    spec:
      containers:
      - name: ctr
        image: nigelpoulton/k8sbook:1.0
        ports:
        - containerPort: 8080     