apiVersion: v1
kind: Service
metadata:
  name: cluster-ip
spec:
  type: ClusterIP
  ports:
  - port:  9000
    targetPort: 8080
  selector:
    course: ckad
  ipFamilyPolicy: PreferDualStack #ipv4 and ipv6 address if you support that