apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp5 #lke-wait minikube name
provisioner: k8s.io/minikube-hostpath #linodebs.csi.linode.com minikube provisioner
reclaimPolicy: Delete
allowVolumeExpansion: false
volumeBindingMode: WaitForFirstConsumer